package dev.momostudios.coldsweat.core.init;

import dev.momostudios.coldsweat.ColdSweat;
import dev.momostudios.coldsweat.api.event.core.BlockTempRegisterEvent;
import dev.momostudios.coldsweat.api.event.core.TempModifierRegisterEvent;
import dev.momostudios.coldsweat.api.temperature.modifier.*;
import dev.momostudios.coldsweat.api.temperature.block_temp.*;
import dev.momostudios.coldsweat.api.registry.BlockTempRegistry;
import dev.momostudios.coldsweat.api.registry.TempModifierRegistry;
import dev.momostudios.coldsweat.util.config.ConfigHelper;
import net.minecraft.block.Block;
import net.minecraft.block.BlockState;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.util.math.BlockPos;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.fml.common.Mod;
import dev.momostudios.coldsweat.config.ColdSweatConfig;
import dev.momostudios.coldsweat.util.math.CSMath;
import net.minecraftforge.fml.event.server.FMLServerStartedEvent;

import java.util.ArrayList;
import java.util.List;

@Mod.EventBusSubscriber
public class TempModifierInit
{
    // Trigger registry events
    @SubscribeEvent
    public static void registerServer(FMLServerStartedEvent event)
    {
        rebuildRegistries();
    }

    public static void rebuildRegistries()
    {
        TempModifierRegistry.flush();
        BlockTempRegistry.flush();

        try { MinecraftForge.EVENT_BUS.post(new TempModifierRegisterEvent()); }
        catch (Exception e)
        {
            ColdSweat.LOGGER.error("Registering TempModifiers failed!");
            e.printStackTrace();
        }

        try { MinecraftForge.EVENT_BUS.post(new BlockTempRegisterEvent()); }
        catch (Exception e)
        {
            ColdSweat.LOGGER.error("Registering BlockTemps failed!");
            e.printStackTrace();
        }
    }

    // Register BlockTemps
    @SubscribeEvent
    public static void registerBlockTemps(BlockTempRegisterEvent event)
    {
        // Add BlockTemps auto-generated by config
        for (List<Object> effectBuilder : ColdSweatConfig.getInstance().getBlockTemps())
        {
            try
            {
                // Check if required fields are present
                if (!(effectBuilder.get(0) instanceof String)
                || !(effectBuilder.get(1) instanceof Number)
                || !(effectBuilder.get(2) instanceof Number))
                {
                    throw new Exception("Invalid BlockTemp format");
                }

                String[] blockIDs = ((String) effectBuilder.get(0)).split(",");

                final double temp    = ((Number) effectBuilder.get(1)).doubleValue();
                final double range   = ((Number) effectBuilder.get(2)).doubleValue();
                final boolean weaken = effectBuilder.size() < 4 || !(effectBuilder.get(3) instanceof Boolean) || (boolean) effectBuilder.get(3);

                final double maxChange = effectBuilder.size() == 5 && effectBuilder.get(4) instanceof Number
                        ? ((Number) effectBuilder.get(4)).doubleValue()
                        : Double.MAX_VALUE;

                final double maxEffect = temp > 0 ?  maxChange :  Double.MAX_VALUE;
                final double minEffect = temp < 0 ? -maxChange : -Double.MAX_VALUE;

                List<Block> effectBlocks = new ArrayList<>();

                for (String id : blockIDs)
                {
                    effectBlocks.addAll(ConfigHelper.getBlocks(id));
                }

                event.register(
                        new BlockTemp(effectBlocks.toArray(new Block[0]))
                        {
                            @Override
                            public double getTemperature(PlayerEntity player, BlockState state, BlockPos pos, double distance)
                            {
                                return weaken ? CSMath.blend(temp, 0, distance, 0.5, range) : temp;
                            }

                            @Override
                            public double maxEffect()
                            {
                                return maxEffect;
                            }

                            @Override
                            public double minEffect()
                            {
                                return minEffect;
                            }
                        });
            }
            catch (Exception e)
            {
                ColdSweat.LOGGER.error("Invalid configuration for BlockTemps in config file \"main.toml\"");
                e.printStackTrace();
                break;
            }
        }

        event.register(new LavaBlockTemp());
        event.register(new FurnaceBlockTemp());
        event.register(new CampfireBlockTemp());
        event.register(new IceboxBlockTemp());
        event.register(new BoilerBlockTemp());
        event.register(new SoulCampfireBlockTemp());
        event.register(new NetherPortalBlockTemp());
    }

    // Register TempModifiers
    @SubscribeEvent
    public static void registerTempModifiers(TempModifierRegisterEvent event)
    {
        String sereneSeasons = "dev.momostudios.coldsweat.api.temperature.modifier.compat.SereneSeasonsTempModifier";
        String betterWeather = "dev.momostudios.coldsweat.api.temperature.modifier.compat.BetterWeatherTempModifier";

        event.register(new BlockTempModifier());
        event.register(new BiomeTempModifier());
        event.register(new DepthTempModifier());
        event.register(new InsulationTempModifier());
        event.register(new MountTempModifier());
        event.register(new WaterskinTempModifier());
        event.register(new SoulLampTempModifier());
        event.register(new WaterTempModifier());
        event.register(new HearthTempModifier());
        event.register(new FoodTempModifier());

        if (ModList.get().isLoaded("sereneseasons"))
        {
            try { event.register((TempModifier) Class.forName(sereneSeasons).getConstructor().newInstance()); }
            catch (Exception ignored) {}
        }
        if (ModList.get().isLoaded("betterweather"))
        {
            try { event.register((TempModifier) Class.forName(betterWeather).getConstructor().newInstance()); }
            catch (Exception ignored) {}
        }

        if (ModList.get().isLoaded("sereneseasons") && ModList.get().isLoaded("betterweather"))
            ColdSweat.LOGGER.warn("Multiple seasons mods are present! Cold Sweat will default to using Serene Seasons...");
    }
}
