package dev.momostudios.coldsweat.core.event;

import dev.momostudios.coldsweat.ColdSweat;
import dev.momostudios.coldsweat.api.event.core.BlockEffectRegisterEvent;
import dev.momostudios.coldsweat.api.event.core.TempModifierRegisterEvent;
import dev.momostudios.coldsweat.api.temperature.modifier.*;
import dev.momostudios.coldsweat.api.temperature.block_effect.*;
import dev.momostudios.coldsweat.api.registry.BlockEffectRegistry;
import dev.momostudios.coldsweat.api.registry.TempModifierRegistry;
import net.minecraft.block.Block;
import net.minecraft.block.BlockState;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.math.BlockPos;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.world.WorldEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.fml.common.Mod;
import dev.momostudios.coldsweat.config.ColdSweatConfig;
import dev.momostudios.coldsweat.util.math.CSMath;

import java.util.List;

@Mod.EventBusSubscriber
public class InitTempModifiers
{
    // Trigger TempModifierEvent.Init
    @SubscribeEvent
    public static void registerTempModifiers(WorldEvent.Load event)
    {
        TempModifierRegistry.flush();
        BlockEffectRegistry.flush();

        try { MinecraftForge.EVENT_BUS.post(new TempModifierRegisterEvent()); }
        catch (Exception e)
        {
            ColdSweat.LOGGER.error("Registering TempModifiers failed!");
            e.printStackTrace();
        }

        try { MinecraftForge.EVENT_BUS.post(new BlockEffectRegisterEvent()); }
        catch (Exception e)
        {
            ColdSweat.LOGGER.error("Registering BlockEffects failed!");
            e.printStackTrace();
        }
    }

    // Register BlockEffects
    @SubscribeEvent
    public static void registerBlockEffects(BlockEffectRegisterEvent event)
    {
        event.register(new LavaBlockEffect());
        event.register(new FurnaceBlockEffect());
        event.register(new CampfireBlockEffect());
        event.register(new IceboxBlockEffect());
        event.register(new BoilerBlockEffect());
        event.register(new SoulCampfireBlockEffect());
        event.register(new NetherPortalBlockEffect());

        // Add BlockEffects auto-generated by config
        for (List<Object> effectBuilder : ColdSweatConfig.getInstance().getBlockEffects())
        {
            try
            {
                // Check if required fields are present
                if (!(effectBuilder.get(0) instanceof String)
                || !(effectBuilder.get(1) instanceof Number)
                || !(effectBuilder.get(2) instanceof Number))
                {
                    throw new Exception("Invalid BlockEffect format");
                }

                String[] blockIDs = ((String) effectBuilder.get(0)).split(",");

                final double temp    = ((Number) effectBuilder.get(1)).doubleValue();
                final double range   = ((Number) effectBuilder.get(2)).doubleValue();
                final boolean weaken = effectBuilder.size() < 4 || !(effectBuilder.get(2) instanceof Boolean) || (boolean) effectBuilder.get(3);

                final double maxTemp = effectBuilder.size() >= 5 && effectBuilder.get(3) instanceof Number
                        ? ((Number) effectBuilder.get(4)).doubleValue()
                        : Double.MAX_VALUE;

                final double minTemp = effectBuilder.size() >= 6 && effectBuilder.get(4) instanceof Number
                        ? ((Number) effectBuilder.get(5)).doubleValue()
                        : -Double.MAX_VALUE;

                event.register(
                        new BlockEffect()
                        {
                            @Override
                            public double getTemperature(PlayerEntity player, BlockState state, BlockPos pos, double distance)
                            {
                                return weaken ? CSMath.blend(temp, 0, distance, 0.5, range) : temp;
                            }

                            @Override
                            public boolean hasBlock(Block block)
                            {
                                for (String id : blockIDs)
                                {
                                    if (block.getRegistryName().equals(new ResourceLocation(id)))
                                        return true;
                                }
                                return false;
                            }

                            @Override
                            public double maxEffect()
                            {
                                return maxTemp;
                            }

                            @Override
                            public double minEffect()
                            {
                                return minTemp;
                            }
                        });
            }
            catch (Exception e)
            {
                ColdSweat.LOGGER.warn("Invalid configuration for BlockEffects in config file \"main.toml\"");
                e.printStackTrace();
                break;
            }
        }
    }

    // Register TempModifiers
    @SubscribeEvent
    public static void registerTempModifiers(TempModifierRegisterEvent event)
    {
        String sereneseasons = "dev.momostudios.coldsweat.api.temperature.modifier.compat.SereneSeasonsTempModifier";
        String betterweather = "dev.momostudios.coldsweat.api.temperature.modifier.compat.BetterWeatherTempModifier";

        event.register(new BlockTempModifier());
        event.register(new BiomeTempModifier());
        event.register(new DepthTempModifier());
        event.register(new InsulationTempModifier());
        event.register(new MountTempModifier());
        event.register(new TimeTempModifier());
        event.register(new WaterskinTempModifier());
        event.register(new HellLampTempModifier());
        event.register(new WaterTempModifier());
        event.register(new HearthTempModifier());
        event.register(new FoodTempModifier());

        if (ModList.get().isLoaded("sereneseasons"))
        {
            try { event.register((TempModifier) Class.forName(sereneseasons).getConstructor().newInstance()); }
            catch (Exception e) {}
        }
        if (ModList.get().isLoaded("betterweather"))
        {
            try { event.register((TempModifier) Class.forName(betterweather).getConstructor().newInstance()); }
            catch (Exception e) {}
        }

        if (ModList.get().isLoaded("sereneseasons") && ModList.get().isLoaded("betterweather"))
            ColdSweat.LOGGER.warn("Multiple seasons mods are present! This may cause issues!");
    }
}
